// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projektReact.Server.ProjektWPF.Data;

#nullable disable

namespace projektReact.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250409111019_mig6")]
    partial class mig6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projektReact.Server.DataModels.Ingredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IngredientName = "Spaghetti",
                            RecipeId = 1L,
                            Weight = 200f
                        },
                        new
                        {
                            Id = 2L,
                            IngredientName = "Ground Beef",
                            RecipeId = 1L,
                            Weight = 300f
                        },
                        new
                        {
                            Id = 3L,
                            IngredientName = "Tomato Sauce",
                            RecipeId = 1L,
                            Weight = 150f
                        },
                        new
                        {
                            Id = 4L,
                            IngredientName = "Onion",
                            RecipeId = 1L,
                            Weight = 50f
                        },
                        new
                        {
                            Id = 5L,
                            IngredientName = "Garlic",
                            RecipeId = 1L,
                            Weight = 10f
                        },
                        new
                        {
                            Id = 6L,
                            IngredientName = "Flour",
                            RecipeId = 2L,
                            Weight = 200f
                        },
                        new
                        {
                            Id = 7L,
                            IngredientName = "Milk",
                            RecipeId = 2L,
                            Weight = 300f
                        },
                        new
                        {
                            Id = 8L,
                            IngredientName = "Eggs",
                            RecipeId = 2L,
                            Weight = 100f
                        },
                        new
                        {
                            Id = 9L,
                            IngredientName = "Sugar",
                            RecipeId = 2L,
                            Weight = 30f
                        },
                        new
                        {
                            Id = 10L,
                            IngredientName = "Baking Powder",
                            RecipeId = 2L,
                            Weight = 10f
                        },
                        new
                        {
                            Id = 11L,
                            IngredientName = "Chicken Breast",
                            RecipeId = 3L,
                            Weight = 400f
                        },
                        new
                        {
                            Id = 12L,
                            IngredientName = "Coconut Milk",
                            RecipeId = 3L,
                            Weight = 200f
                        },
                        new
                        {
                            Id = 13L,
                            IngredientName = "Curry Powder",
                            RecipeId = 3L,
                            Weight = 15f
                        },
                        new
                        {
                            Id = 14L,
                            IngredientName = "Onion",
                            RecipeId = 3L,
                            Weight = 100f
                        },
                        new
                        {
                            Id = 15L,
                            IngredientName = "Garlic",
                            RecipeId = 3L,
                            Weight = 20f
                        },
                        new
                        {
                            Id = 16L,
                            IngredientName = "Cucumber",
                            RecipeId = 4L,
                            Weight = 150f
                        },
                        new
                        {
                            Id = 17L,
                            IngredientName = "Tomatoes",
                            RecipeId = 4L,
                            Weight = 200f
                        },
                        new
                        {
                            Id = 18L,
                            IngredientName = "Feta Cheese",
                            RecipeId = 4L,
                            Weight = 100f
                        },
                        new
                        {
                            Id = 19L,
                            IngredientName = "Black Olives",
                            RecipeId = 4L,
                            Weight = 80f
                        },
                        new
                        {
                            Id = 20L,
                            IngredientName = "Red Onion",
                            RecipeId = 4L,
                            Weight = 50f
                        },
                        new
                        {
                            Id = 21L,
                            IngredientName = "Flour",
                            RecipeId = 5L,
                            Weight = 250f
                        },
                        new
                        {
                            Id = 22L,
                            IngredientName = "Cocoa Powder",
                            RecipeId = 5L,
                            Weight = 50f
                        },
                        new
                        {
                            Id = 23L,
                            IngredientName = "Sugar",
                            RecipeId = 5L,
                            Weight = 200f
                        },
                        new
                        {
                            Id = 24L,
                            IngredientName = "Eggs",
                            RecipeId = 5L,
                            Weight = 100f
                        },
                        new
                        {
                            Id = 25L,
                            IngredientName = "Butter",
                            RecipeId = 5L,
                            Weight = 100f
                        });
                });

            modelBuilder.Entity("projektReact.Server.DataModels.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Classic Italian pasta dish with meat sauce.",
                            Title = "Spaghetti Bolognese"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Fluffy pancakes perfect for breakfast.",
                            Title = "Pancakes"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Spicy and savory Indian-style curry.",
                            Title = "Chicken Curry"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Fresh salad with feta cheese and olives.",
                            Title = "Greek Salad"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Rich and moist chocolate dessert.",
                            Title = "Chocolate Cake"
                        });
                });

            modelBuilder.Entity("projektReact.Server.DataModels.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "sdadsaookl",
                            Password = "AQAAAAIAAYagAAAAEFacXzmHLjAGh4bGa5X2lO32T424kyKeGpsAVvSYAYr529ULQQ7tUrVJ9E/bFTR7mA==",
                            Username = "admin@wp.pl"
                        });
                });

            modelBuilder.Entity("projektReact.Server.DataModels.Ingredient", b =>
                {
                    b.HasOne("projektReact.Server.DataModels.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("projektReact.Server.DataModels.Recipe", b =>
                {
                    b.HasOne("projektReact.Server.DataModels.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("projektReact.Server.DataModels.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("projektReact.Server.DataModels.User", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
